version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /opt/flask-mysql-boilerplate:/counter_app
    links:
      - db:mysql
    container_name: counterappmysql_web_1
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
        PORT: 5000
        SECRET_KEY: 'you-will-never-guess'
        DEBUG: 1 # can't pass True here, but 1 works
        MYSQL_ROOT_PASSWORD: rootpass
        DB_USERNAME: counter_user
        DB_PASSWORD: counter_password
        DB_HOST: mysql
        DATABASE_NAME: counter
  db:
    image: mysql:5.7
    restart: always
    container_name: counterappmysql_db_1
    ports:
      - "3306:3306"
    environment:
        MYSQL_USER: counter_user
        MYSQL_PASSWORD: counter_password
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_DATABASE: counter
